[package]
name = "day14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# A lightweight logging facade for Rust 
log = "0.4.14"
# A logging implementation for `log` which is configured via an environment variable. 
env_logger = "0.9.0"
# Flexible concrete Error type built on std::error::Error
anyhow = "1.0.51"
# ✨ Lookup and iterate over emoji names, shortcodes, and groups.
emojis = "0.2.1"
# An implementation of regular expressions for Rust. This implementation uses finite automata and g…
regex = "1.5.4"
# __attribute__((constructor)) for Rust
ctor = "0.1.21"
