[package]
name = "day10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# A lightweight logging facade for Rust 
log = "0.4.14"
# A logging implementation for `log` which is configured via an environment variable. 
env_logger = "0.9.0"
# Flexible concrete Error type built on std::error::Error
anyhow = "1.0.51"
# ✨ Lookup and iterate over emoji names, shortcodes, and groups.
emojis = "0.2.1"
# Extra iterator adaptors, iterator methods, free functions, and macros.
itertools = "0.10.3"